kind: pipeline
type: docker
name: default

steps:

- name: setup
  image: kameshsampath/gitops-on-k3s-installer
  pull: never
  settings:
    # delete_cluster: true
    create_cluster: false
    k3d_cluster_name: my-gitops-demo
    install_components:
      - gitea
      - argocd
    check_install: true
  volumes:
  - name: docker-config
    path: /var/run/docker.sock
volumes:
  - name: docker-config
    host:
     path: /var/run/docker.sock